# Generated by Django 3.2.8 on 2021-11-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('CID', models.IntegerField(null=True)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(null=True)),
                ('Type', models.CharField(max_length=100)),
                ('Capacity', models.IntegerField()),
                ('Rate', models.CharField(max_length=100)),
                ('PickLocation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.IntegerField(null=True)),
                ('CID', models.IntegerField(null=True)),
                ('PickDate', models.DateField(blank=True)),
                ('DropDate', models.DateField(blank=True)),
                ('PickLocation', models.CharField(max_length=100)),
                ('DropLocation', models.CharField(max_length=100)),
            ],
        ),
    ]
